### ISSUE TITLE
Add new comment

### ISSUE THREAD

**Issue by berkus** [FreeFeed/freefeed-react-client#13]
**@todo**

**Comment by smallq-git** [comment]
Can't add new comment: unhandled promise in console and a picture failing to load (probably throbber?).

![image](https://cloud.githubusercontent.com/assets/7983303/10350689/2c2ff34a-6d4e-11e5-88f2-c25ce341f464.png)

Unhandled promise rejection TypeError: Can't call method on  undefined
    at TypeError (native)
    at e.exports (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:2:14947)
    at e.exports (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:22:6347)
    at o.from (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:25:2381)
    at t.default (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:24:29159)
    at l (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:24:23227)
    at https://george.freefeed.net/app-6894ca89f37bb6c52943.js:35:11174
    at https://george.freefeed.net/app-6894ca89f37bb6c52943.js:23:22777
    at Array.reduce (native)
    at Object.n [as default] (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:23:22744)

**Comment by berkus** [comment]
Handled in #55
