### ISSUE TITLE
Can't add new comment: unhandled promise in console

### ISSUE THREAD

**Issue by berkus** [FreeFeed/freefeed-react-client#55]
@smallq-git:
See comments in #13 for details of the bug:

![](https://cloud.githubusercontent.com/assets/7983303/10350689/2c2ff34a-6d4e-11e5-88f2-c25ce341f464.png)

```
Unhandled promise rejection TypeError: Can't call method on undefined
at TypeError (native)
at e.exports (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:2:14947)
at e.exports (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:22:6347)
at o.from (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:25:2381)
at t.default (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:24:29159)
at l (https://george.freefeed.net/app-6894ca89f37bb6c52943.js:24:23227)
at https://george.freefeed.net/app-6894ca89f37bb6c52943.js:35:11174
at https://george.freefeed.net/app-6894ca89f37bb6c52943.js:23:22777
at Array.reduce (native)
at Object.n as default
```

**Comment by ujenjt** [comment]
Looks like, this case about edit comment, not add. If yes, my last PR https://github.com/FreeFeed/freefeed-react-client/pull/62 fixes this.
